# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testing123' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testing123
	pod ‘Firebase’ 
   	pod ‘Firebase/Database’
	pod ‘Firebase/Storage’
	pod 'Firebase/Core'
	pod 'Firebase/AdMob'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/DynamicLinks'
	pod 'Firebase/Invites'
	pod 'Firebase/Messaging'
	pod 'Firebase/Performance'
end
